#pragma once

#define SPLIT_LAYER_STATE_ENABLE
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_BREATHING
#define PERMISSIVE_HOLD

#define ACHORDION_STREAK

#define TAPPING_TERM 200
#define TAPPING_TERM_PER_KEY
